fix(Cookies): Optimierte Cookie Generierung
iamnotturner/vaccipy pull request #395
Opened 2021-06-09 11:40 UTC by sinun98

2021-06-09 11:44 UTC, sinun98 commented
@pancakeDevelopment Kannst du das mal testen?

2021-06-09 11:52 UTC, pancakeDevelopment commented
<img width="439" alt="test_geht" src="https://user-images.githubusercontent.com/43381667/121349490-dcca0000-c929-11eb-8ea4-ba51a4eaf8d0.PNG">

Gab nur ein Problem bei mir "self is not defined"

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 2141, in shutdown
    h.flush()
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 1066, in flush
    if self.stream and hasattr(self.stream, "flush"):
RuntimeError: wrapped C/C++ object of type EigenerStream has been deleted
```

2021-06-09 12:39 UTC, iamnotturner commented
@sinun98 können wir den `Browser-Cookie generiert ...`-Log von `success` wieder zu `info` machen? das ist imo bisschen too much für ne einfache Cookie-Generierung, oder?

2021-06-09 13:08 UTC, sinun98 commented
> <img alt="test_geht" width="439" src="https://user-images.githubusercontent.com/43381667/121349490-dcca0000-c929-11eb-8ea4-ba51a4eaf8d0.PNG">
> 
> Ging sofort durch, ohne Probleme! Habe vorher noch nen Test durchgeführt mit dem Release. Mit der neuen Version gings sofort, sogar ohne Selenium.
> Gab nur ein Problem bei mir "self is not defined" **(nach Terminbuchung)**
> 
> ```
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "C:\Program Files\Python39\lib\logging\__init__.py", line 2141, in shutdown
>     h.flush()
>   File "C:\Program Files\Python39\lib\logging\__init__.py", line 1066, in flush
>     if self.stream and hasattr(self.stream, "flush"):
> RuntimeError: wrapped C/C++ object of type EigenerStream has been deleted
> ```
> 
> Edit: Sollte wohl dadurch gelöst sein, oder? #394

Sollte gefixt sein ja

2021-06-09 13:22 UTC, sinun98 commented
> @sinun98 können wir den `Browser-Cookie generiert ...`-Log von `success` wieder zu `info` machen? das ist imo bisschen too much für ne einfache Cookie-Generierung, oder?

#399

2021-06-09 13:27 UTC, iamnotturner requested changes

2021-06-09 13:27 UTC, iamnotturner commented on tools/its.py
> +        time.sleep(1.5)
wozu der Sleep hier?

2021-06-09 13:27 UTC, iamnotturner commented on tools/its.py
> +            except:
```suggestion
            except Exception as exc:
```

2021-06-09 13:27 UTC, iamnotturner commented on tools/its.py
> +
```suggestion

    # Zufälliges anklicken von 10-15 Elementen auf der Seite
    # ggf. werden andere Seiten aufgerufen
```

2021-06-09 13:31 UTC, iamnotturner requested changes

2021-06-09 13:31 UTC, iamnotturner commented on tools/its.py
> +            try:
```suggestion
        # Zufälliges anklicken von 10-15 Elementen auf der Seite
        # ggf. werden andere Seiten aufgerufen
        for i in range(randint(10, 15)):
            try:
```

2021-06-09 13:31 UTC, iamnotturner commented on tools/its.py
> +            try:
zu wenige spaces

2021-06-09 13:34 UTC, iamnotturner approved these changes

2021-06-09 13:36 UTC, merged

2021-06-12 10:24 UTC, andreas-becker commented
Bei mir im Beta-Branch scheitert das Impf-Code generieren immer noch an der Botprotection.

2021-06-12 10:38 UTC, iamnotturner commented
> Bei mir im Beta-Branch scheitert das Impf-Code generieren immer noch an der Botprotection.

@andreas-becker eher wieder, oder? bis gestern ging's ohne Probleme, zumindest bei mir